config/routes.rb
Rails.application.routes.draw do
  resources :weekly_updates

  resources :projects

  resources :people

  get 'weekly/:id' => 'person_updates#index', as: :weekly
  get 'weekly/new/:person/:project' => 'person_updates#new', as: :new_update 

  root 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  validates :name, presence: true
  validates :name, length: { minimum: 2}
  has_many :weekly_updates
  has_many :projects, :through => :weekly_updates

# Returns a hash whose keys are project objects, and whose values are
# arrays of WeeklyUpdates, ordered with the most recent weekstart first.
#
# Pass either a Date object or :all
  def weekly_updates_by_project(since)
    since = Date.new(2000,01,01) if since == :all
    self.weekly_updates.where(["weekstart > ?",since]).order("project_id, weekstart desc").group_by {|w| w.project}
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
    #SF: amended because it's not really that scary
      #params[:person]
      params.require(:person).permit(:name)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.haml
= form_for @person do |f|
  - if @person.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person.errors.count, "error")} prohibited this person from being saved:"
      %ul
        - @person.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :name, :caption => "Name: ", :class => 'person_label'
    = f.text_field :name, :class => 'person_text'
  .actions
    = f.submit 'Save'

app/views/people/edit.html.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @person
\|
= link_to 'Back', people_path

app/views/people/index.html.haml
%h1 Listing people

%table
  %tr
    %th
    %th
    %th

  - @people.each do |person|
    %tr
      %td= link_to person.name, person
      %td= link_to 'Edit', edit_person_path(person)
      %td= link_to 'Destroy', person, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Person', new_person_path

app/views/people/new.html.haml
%h1 New person

= render 'form'

= link_to 'Back', people_path

app/views/people/show.html.haml
%p#notice= notice

.name= @person.name

= link_to 'Projects', weekly_path(@person)
= link_to 'Edit', edit_person_path(@person)
\|
= link_to 'Back', people_path