config/routes.rb
Rails.application.routes.draw do
  resources :weekly_updates

  resources :projects

  resources :people

  get 'weekly/:id' => 'person_updates#index', as: :weekly
  get 'weekly/new/:person/:project' => 'person_updates#new', as: :new_update 

  root 'people#index'

end

app/controllers/person_updates_controller.rb
class PersonUpdatesController < ApplicationController
  before_action :set_person, only: [:index, :show, :edit, :update, :destroy]

  def index
#    @updates = @person.weekly_updates_by_project(Date.today-7)
    @updates = @person.weekly_updates_by_project(:all)
  end

  def new
    person = Person.find(params[:person])
    project = Project.find(params[:project])
    latest = project.latest_update
    wu = WeeklyUpdate.new(:person => person, :project => project, :rag => latest.rag, :percent => latest.percent, :comment => latest.comment)
    wu.save
    redirect_to edit_weekly_update_path(wu)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

end

app/helpers/person_updates_helper.rb
module PersonUpdatesHelper
end

app/views/person_updates/_form.html.haml
= form_for @person_update do |f|
  - if @person_update.errors.any?
    #error_explanation
      %h2= "#{pluralize(@person_update.errors.count, "error")} prohibited this update from being saved:"
      %ul
        - @person_update.errors.full_messages.each do |msg|
          %li= msg
  %p
    = f.label :project, :caption => "Project: ", :class => 'update_label'
    = f.select :project, options_from_collection_for_select(@projects, 'id', 'name')
  %p
    = f.label :weekstart, :caption => "Week: ", :class => 'update_label'
    = f.text :weekstart, :class => 'update_field'
  %p
    = f.label :rag, :caption => "Status", :class => 'update_label'
    = f.select :rag, options_for_select([['Red','Red'],['Amber','Amber'],['Green','Green']])
  %p
    = f.label :percent, :caption => "Percent: ", :class => 'update_label'
    = f.text :percent, :class => 'update_field'
  %p
    = f.label :comment, :caption => "Comment: ", :class => 'update_label'
    = f.text :comment, :class => 'update_field'
  .actions
    = f.submit 'Save'

app/views/person_updates/index.html.haml
%h1
  Weekly updates for
  %span.person= @person.name

%table
  %tr
    %th Project
    %th Person
    %th Weekstart
    %th Rag
    %th Percent
    %th Comment
    %th

  - @updates.each do |project,weeklies|
    - wu = weeklies.first
    %tr
      %td= project.name
      %td= wu.person.name
      %td= wu.weekstart
      %td= wu.rag
      %td= wu.percent
      %td= wu.comment
      %td
        - if wu.is_current_week?
          = link_to 'Edit', edit_weekly_update_path(wu)
        - else
          = link_to 'New', new_update_path(wu.person, wu.project)

%br

= link_to 'Add a new project'