config/routes.rb
Rails.application.routes.draw do
  resources :weekly_updates

  resources :projects

  resources :people

  get 'weekly/:id' => 'person_updates#index', as: :weekly
  get 'weekly/new/:person/:project' => 'person_updates#new', as: :new_update 

  root 'people#index'

end

app/models/weekly_update.rb
class WeeklyUpdate < ActiveRecord::Base
  belongs_to :project
  belongs_to :person
  validates :project, :presence => true
  validates :person, :presence => true
  validates :rag, :inclusion => %w(Red Amber Green)
  validates :weekstart, :presence => true

  after_initialize do
    if new_record?
        self.rag = "Green"
        self.weekstart = recent_monday
    end
  end

  def for_person(p)
    WeeklyUpdate.find(:where => person_id = p.id)
  end

  def is_current_week?
    self.weekstart == recent_monday
  end

  private
    def recent_monday
      d = Date.parse("Monday")
      if d > Date.today
        d - 7
      else
        d
      end
    end
                 
end

app/controllers/weekly_updates_controller.rb
class WeeklyUpdatesController < ApplicationController
  before_action :set_weekly_update, only: [:show, :edit, :update, :destroy]

  # GET /weekly_updates
  # GET /weekly_updates.json
  def index
    @weekly_updates = WeeklyUpdate.all
  end

  # GET /weekly_updates/1
  # GET /weekly_updates/1.json
  def show
  end

  # GET /weekly_updates/new
  def new
    @weekly_update = WeeklyUpdate.new
  end

  # GET /weekly_updates/1/edit
  def edit
  end

  # # POST /weekly_updates
  # # POST /weekly_updates.json
  # def create
  #   @weekly_update = WeeklyUpdate.new(weekly_update_params)
  #
  #   respond_to do |format|
  #     if @weekly_update.save
  #       format.html { redirect_to @weekly_update, notice: 'Weekly update was successfully created.' }
  #       format.json { render :show, status: :created, location: @weekly_update }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @weekly_update.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /weekly_updates/1
  # PATCH/PUT /weekly_updates/1.json
  def update
    respond_to do |format|
      if @weekly_update.update(weekly_update_params)
        format.html { redirect_to weekly_url(@weekly_update.person), notice: 'Weekly update was successfully updated.' }
        format.json { render :show, status: :ok, location: @weekly_update }
      else
        format.html { render :edit }
        format.json { render json: @weekly_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_updates/1
  # DELETE /weekly_updates/1.json
  def destroy
    @weekly_update.destroy
    respond_to do |format|
      format.html { redirect_to weekly_updates_url, notice: 'Weekly update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#  private
    # Use callbacks to share common setup or constraints between actions.
    def set_weekly_update
      @weekly_update = WeeklyUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def weekly_update_params
      #params.require(:weekly_update).permit(:project_id, :person_id, :weekstart, :rag, :percent, :comment)
      params.require(:weekly_update).permit! #(:project, :person, :weekstart, :rag, :percent, :comment)
    end
end

app/helpers/weekly_updates_helper.rb
module WeeklyUpdatesHelper
end

app/views/weekly_updates/_form.html.haml
= form_for @weekly_update do |f|
  - if @weekly_update.errors.any?
    #error_explanation
      %h2= "#{pluralize(@weekly_update.errors.count, "error")} prohibited this weekly_update from being saved:"
      %ul
        - @weekly_update.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :project
    = f.label @weekly_update.project.name
  .field
    = f.label :person
    = f.label @weekly_update.person.name
  .field
    = f.label :weekstart
    = f.date_select :weekstart
  .field
    = f.label :rag
    = f.text_field :rag
  .field
    = f.label :percent
    = f.number_field :percent
  .field
    = f.label :comment
    = f.text_area :comment
  .actions
    = f.submit 'Save'

app/views/weekly_updates/edit.html.haml
%h1 Editing weekly_update

= render 'form'

= link_to 'Show', @weekly_update
\|
= link_to 'Back', weekly_updates_path

app/views/weekly_updates/index.html.haml
%h1 Listing weekly_updates

%table
  %tr
    %th Project
    %th Person
    %th Weekstart
    %th Rag
    %th Percent
    %th Comment
    %th
    %th
    %th

  - @weekly_updates.each do |weekly_update|
    %tr
      %td= weekly_update.project
      %td= weekly_update.person
      %td= weekly_update.weekstart
      %td= weekly_update.rag
      %td= weekly_update.percent
      %td= weekly_update.comment
      %td= link_to 'Show', weekly_update
      %td= link_to 'Edit', edit_weekly_update_path(weekly_update)
      %td= link_to 'Destroy', weekly_update, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Weekly update', new_weekly_update_path

app/views/weekly_updates/new.html.haml
%h1 New weekly_update

= render 'form'

= link_to 'Back', weekly_updates_path

app/views/weekly_updates/show.html.haml
%p#notice= notice

%p
  %b Project:
  = @weekly_update.project
%p
  %b Person:
  = @weekly_update.person
%p
  %b Weekstart:
  = @weekly_update.weekstart
%p
  %b Rag:
  = @weekly_update.rag
%p
  %b Percent:
  = @weekly_update.percent
%p
  %b Comment:
  = @weekly_update.comment

= link_to 'Edit', edit_weekly_update_path(@weekly_update)
\|
= link_to 'Back', weekly_updates_path